### ISSUE TITLE
The app is not showing any data , when search any cities

### ISSUE THREAD

**Issue by the-wrong-guy** [Garvnanwani/WeatherApp_PWA#3]
**Error in fetching whether details of cities**

![image](https://user-images.githubusercontent.com/52911853/96082278-8e6a7b80-0ed8-11eb-80ca-64383176b119.png)
![image](https://user-images.githubusercontent.com/52911853/96082397-c96caf00-0ed8-11eb-91c8-b660e6d23018.png)

**Comment by Garvnanwani** [comment]
Thanks for informing, the issue was with api key.
I have fixed it. Should work now
