### ISSUE TITLE
The webapp is not responsive and UI can be further improve

### ISSUE THREAD

**Issue by the-wrong-guy** [Garvnanwani/WeatherApp_PWA#4]
The UI is not looking good, the styles can be further improved and lack of responsiveness to phone users

![image](https://user-images.githubusercontent.com/52911853/96082575-16e91c00-0ed9-11eb-985d-df15e76edc85.png)

**Comment by Garvnanwani** [comment]
I see some part of the responsive issue was because it was unable to fetch data.
I will look into the UI improvement too. Thanks
