### ISSUE TITLE
Thought of React Native?

### ISSUE THREAD

**Issue by OkomoJacob** [Garvnanwani/WeatherApp_PWA#7]
- I really like what you are doing here on GitHub
- I'm currently learning React Native and would like to suggest if this app can run on react native?
- Again I would highly like to contribute.
- Kindly incorporate me into this build.

**Comment by Garvnanwani** [comment]
Really appreciate your attitude towards showing in my repo, but sorry it not in react native, its a pwa that means it can be installed on mobile devices but it will be installed as a browser app so it will run on top of a browser.
But if you want to contribute in any way, you are more than welcome to give some suggestions, make some prs and improve the app

**Comment by OkomoJacob** [comment]
Thank you and noted
